### ISSUE TITLE
Add ability to generate custom transforms

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-transforms#1]
By introducing a `customTransforms` (or just `transforms`?) option which would let you control the full value of the `transform` property. Maybe the `none` value could be part of it by default?

**Comment by magicspon** [comment]
this kinda thing?!

```javascript
{
 'my-new-jumper': 'translate3d(50%, 100%, 0) rotate(10deg)'
}

```

**Comment by benface** [comment]
Yeah! Do you think that would be useful to add, or not since it's already super easy to create custom utilities in Tailwind?

**Comment by benface** [comment]
Done in ffa695e38829a1264100296f1184c43c6a0ec6dd
