### ISSUE TITLE
Add variants.

### ISSUE THREAD

**Issue by tw1t611** [benface/tailwindcss-transforms#17]
Please add variants to use the transforms on, for example `hover:` and `focus:`.

**Comment by benface** [comment]
@tw1t611 This is already customizable. You can add the following to your Tailwind config to enable `hover` and `focus` variants on all the transform utilities (by default, only `responsive` is enabled):

```
  variants: {
    transform: ['hover', 'focus', 'responsive'],
    transformOrigin: ['hover', 'focus', 'responsive'],
    translate: ['hover', 'focus', 'responsive'],
    scale: ['hover', 'focus', 'responsive'],
    rotate: ['hover', 'focus', 'responsive'],
    skew: ['hover', 'focus', 'responsive'],
    perspective: ['hover', 'focus', 'responsive'],
    perspectiveOrigin: ['hover', 'focus', 'responsive'],
    transformStyle: ['hover', 'focus', 'responsive'],
    backfaceVisibility: ['hover', 'focus', 'responsive'],
    transformBox: ['hover', 'focus', 'responsive'],
  },
```

Also, did you know that transforms are coming to Tailwind? You won't need this plugin soon enough (in fact, it will be discontinued as soon as the next version of Tailwind is released): https://github.com/tailwindcss/tailwindcss/pull/1272
